[project]
name = "fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "openai>=1.104.2",
    "requests>=2.32.5",
    "uvicorn>=0.35.0",
]
